# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wiggler_w_ui.ui'
#
# Created: Mon Nov 19 12:12:05 2012
#      by: PyQt4 UI code generator 4.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Wiggler(object):
    def setupUi(self, Wiggler):
        Wiggler.setObjectName(_fromUtf8("Wiggler"))
        Wiggler.resize(504, 257)
        self.layoutWidget = QtGui.QWidget(Wiggler)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 2, 501, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.wig_energy = QtGui.QLineEdit(self.groupBox)
        self.wig_energy.setObjectName(_fromUtf8("wig_energy"))
        self.verticalLayout_2.addWidget(self.wig_energy)
        self.verticalLayout_23.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_11.addWidget(self.label_16)
        self.wig_periods = QtGui.QLineEdit(self.groupBox)
        self.wig_periods.setObjectName(_fromUtf8("wig_periods"))
        self.verticalLayout_11.addWidget(self.wig_periods)
        self.verticalLayout_23.addLayout(self.verticalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.wig_current = QtGui.QLineEdit(self.groupBox)
        self.wig_current.setObjectName(_fromUtf8("wig_current"))
        self.verticalLayout.addWidget(self.wig_current)
        self.verticalLayout_24.addLayout(self.verticalLayout)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.wig_nperiods = QtGui.QLineEdit(self.groupBox)
        self.wig_nperiods.setObjectName(_fromUtf8("wig_nperiods"))
        self.verticalLayout_14.addWidget(self.wig_nperiods)
        self.verticalLayout_24.addLayout(self.verticalLayout_14)
        self.horizontalLayout.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.wig_kx = QtGui.QLineEdit(self.groupBox_2)
        self.wig_kx.setObjectName(_fromUtf8("wig_kx"))
        self.verticalLayout_3.addWidget(self.wig_kx)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.wig_ky = QtGui.QLineEdit(self.groupBox_2)
        self.wig_ky.setObjectName(_fromUtf8("wig_ky"))
        self.verticalLayout_4.addWidget(self.wig_ky)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.advanced_button = QtGui.QPushButton(self.layoutWidget)
        self.advanced_button.setObjectName(_fromUtf8("advanced_button"))
        self.horizontalLayout_3.addWidget(self.advanced_button)
        self.default_button = QtGui.QPushButton(self.layoutWidget)
        self.default_button.setObjectName(_fromUtf8("default_button"))
        self.horizontalLayout_3.addWidget(self.default_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Wiggler)
        QtCore.QMetaObject.connectSlotsByName(Wiggler)
        Wiggler.setTabOrder(self.wig_energy, self.wig_current)
        Wiggler.setTabOrder(self.wig_current, self.wig_periods)
        Wiggler.setTabOrder(self.wig_periods, self.wig_nperiods)
        Wiggler.setTabOrder(self.wig_nperiods, self.wig_kx)
        Wiggler.setTabOrder(self.wig_kx, self.wig_ky)

    def retranslateUi(self, Wiggler):
        Wiggler.setWindowTitle(QtGui.QApplication.translate("Wiggler", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Wiggler", "Machine Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Wiggler", "Beam Energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_energy.setText(QtGui.QApplication.translate("Wiggler", "5.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Wiggler", "Period Length (cm)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_periods.setText(QtGui.QApplication.translate("Wiggler", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_periods.setPlaceholderText(QtGui.QApplication.translate("Wiggler", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Wiggler", "Beam Current (mA)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_current.setText(QtGui.QApplication.translate("Wiggler", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Wiggler", "Number of Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_nperiods.setText(QtGui.QApplication.translate("Wiggler", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Wiggler", "Wiggler Paramters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Wiggler", "Deflection Parameter Kx", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_kx.setText(QtGui.QApplication.translate("Wiggler", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Wiggler", "Deflection Parameter Ky", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_ky.setText(QtGui.QApplication.translate("Wiggler", "8.74", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_button.setText(QtGui.QApplication.translate("Wiggler", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.default_button.setText(QtGui.QApplication.translate("Wiggler", "Default Values", None, QtGui.QApplication.UnicodeUTF8))

