import _pickle as pickle
be=pickle.load(open("..\\pickle\\ws_data.pkl","rb"))
#si=pickle.load(open("..\\mu_data\\Cu.pkl","rb"))
#print(si)
def picklemat(mat): return "\n".join([str(i[0])+"\t"+str(i[1]) for i in mat])
print(be)
print(picklemat(be))
beo=open("..\\mathematica_output\\ws.dat","w") 
#sio=open("..\\mathematica_output\\cu.dat","w")
beo.write(picklemat(be)) 
#sio.write(picklemat(si))
beo.close()
#sio.close()