# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'undulator_ui.ui'
#
# Created: Fri Jul  6 17:13:24 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(589, 570)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 588, 566))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_31.setMargin(0)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.und_title = QtGui.QLineEdit(self.groupBox_4)
        self.und_title.setText(_fromUtf8(""))
        self.und_title.setObjectName(_fromUtf8("und_title"))
        self.verticalLayout_11.addWidget(self.und_title)
        self.verticalLayout_31.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.und_energy = QtGui.QLineEdit(self.groupBox)
        self.und_energy.setObjectName(_fromUtf8("und_energy"))
        self.verticalLayout.addWidget(self.und_energy)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.und_current = QtGui.QLineEdit(self.groupBox)
        self.und_current.setObjectName(_fromUtf8("und_current"))
        self.verticalLayout_2.addWidget(self.und_current)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.verticalLayout_31.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.und_sigx = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigx.setObjectName(_fromUtf8("und_sigx"))
        self.verticalLayout_3.addWidget(self.und_sigx)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.und_sigy = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigy.setObjectName(_fromUtf8("und_sigy"))
        self.verticalLayout_4.addWidget(self.und_sigy)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.und_sigx1 = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigx1.setObjectName(_fromUtf8("und_sigx1"))
        self.verticalLayout_5.addWidget(self.und_sigx1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.und_sigy1 = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigy1.setObjectName(_fromUtf8("und_sigy1"))
        self.verticalLayout_6.addWidget(self.und_sigy1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout_31.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.und_period = QtGui.QLineEdit(self.groupBox_3)
        self.und_period.setObjectName(_fromUtf8("und_period"))
        self.verticalLayout_7.addWidget(self.und_period)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.undn = QtGui.QLabel(self.groupBox_3)
        self.undn.setObjectName(_fromUtf8("undn"))
        self.verticalLayout_8.addWidget(self.undn)
        self.und_nperiods = QtGui.QLineEdit(self.groupBox_3)
        self.und_nperiods.setObjectName(_fromUtf8("und_nperiods"))
        self.verticalLayout_8.addWidget(self.und_nperiods)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.und_kx = QtGui.QLineEdit(self.groupBox_3)
        self.und_kx.setObjectName(_fromUtf8("und_kx"))
        self.verticalLayout_9.addWidget(self.und_kx)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.und_ky = QtGui.QLineEdit(self.groupBox_3)
        self.und_ky.setObjectName(_fromUtf8("und_ky"))
        self.verticalLayout_10.addWidget(self.und_ky)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.verticalLayout_31.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_15.addWidget(self.label_11)
        self.und_distance = QtGui.QLineEdit(self.groupBox_5)
        self.und_distance.setObjectName(_fromUtf8("und_distance"))
        self.verticalLayout_15.addWidget(self.und_distance)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_16.addWidget(self.label_12)
        self.und_xposition = QtGui.QLineEdit(self.groupBox_5)
        self.und_xposition.setObjectName(_fromUtf8("und_xposition"))
        self.verticalLayout_16.addWidget(self.und_xposition)
        self.verticalLayout_24.addLayout(self.verticalLayout_16)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.und_yposition = QtGui.QLineEdit(self.groupBox_5)
        self.und_yposition.setObjectName(_fromUtf8("und_yposition"))
        self.verticalLayout_19.addWidget(self.und_yposition)
        self.verticalLayout_24.addLayout(self.verticalLayout_19)
        self.horizontalLayout_4.addLayout(self.verticalLayout_24)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_17.addWidget(self.label_15)
        self.und_xslit = QtGui.QLineEdit(self.groupBox_5)
        self.und_xslit.setObjectName(_fromUtf8("und_xslit"))
        self.verticalLayout_17.addWidget(self.und_xslit)
        self.verticalLayout_22.addLayout(self.verticalLayout_17)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_20.addWidget(self.label_18)
        self.und_yslit = QtGui.QLineEdit(self.groupBox_5)
        self.und_yslit.setObjectName(_fromUtf8("und_yslit"))
        self.verticalLayout_20.addWidget(self.und_yslit)
        self.verticalLayout_22.addLayout(self.verticalLayout_20)
        self.horizontalLayout_4.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_18.addWidget(self.label_16)
        self.und_xintpoints = QtGui.QLineEdit(self.groupBox_5)
        self.und_xintpoints.setObjectName(_fromUtf8("und_xintpoints"))
        self.verticalLayout_18.addWidget(self.und_xintpoints)
        self.verticalLayout_23.addLayout(self.verticalLayout_18)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_21.addWidget(self.label_17)
        self.und_yintpoints = QtGui.QLineEdit(self.groupBox_5)
        self.und_yintpoints.setObjectName(_fromUtf8("und_yintpoints"))
        self.verticalLayout_21.addWidget(self.und_yintpoints)
        self.verticalLayout_23.addLayout(self.verticalLayout_21)
        self.horizontalLayout_4.addLayout(self.verticalLayout_23)
        self.verticalLayout_25.addLayout(self.horizontalLayout_4)
        self.verticalLayout_31.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_28.addWidget(self.label_20)
        self.und_estart = QtGui.QLineEdit(self.groupBox_6)
        self.und_estart.setObjectName(_fromUtf8("und_estart"))
        self.verticalLayout_28.addWidget(self.und_estart)
        self.horizontalLayout_5.addLayout(self.verticalLayout_28)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_27.addWidget(self.label_21)
        self.und_eend = QtGui.QLineEdit(self.groupBox_6)
        self.und_eend.setObjectName(_fromUtf8("und_eend"))
        self.verticalLayout_27.addWidget(self.und_eend)
        self.horizontalLayout_5.addLayout(self.verticalLayout_27)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_26.addWidget(self.label_22)
        self.und_edivisions = QtGui.QLineEdit(self.groupBox_6)
        self.und_edivisions.setObjectName(_fromUtf8("und_edivisions"))
        self.verticalLayout_26.addWidget(self.und_edivisions)
        self.horizontalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_29.addLayout(self.horizontalLayout_5)
        self.verticalLayout_31.addWidget(self.groupBox_6)
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_30.addWidget(self.label_23)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.advanced_button = QtGui.QPushButton(self.layoutWidget)
        self.advanced_button.setObjectName(_fromUtf8("advanced_button"))
        self.horizontalLayout_6.addWidget(self.advanced_button)
        self.verticalLayout_30.addLayout(self.horizontalLayout_6)
        self.verticalLayout_31.addLayout(self.verticalLayout_30)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.und_title, self.und_energy)
        Dialog.setTabOrder(self.und_energy, self.und_current)
        Dialog.setTabOrder(self.und_current, self.und_sigx)
        Dialog.setTabOrder(self.und_sigx, self.und_sigy)
        Dialog.setTabOrder(self.und_sigy, self.und_sigx1)
        Dialog.setTabOrder(self.und_sigx1, self.und_sigy1)
        Dialog.setTabOrder(self.und_sigy1, self.und_period)
        Dialog.setTabOrder(self.und_period, self.und_nperiods)
        Dialog.setTabOrder(self.und_nperiods, self.und_kx)
        Dialog.setTabOrder(self.und_kx, self.und_ky)
        Dialog.setTabOrder(self.und_ky, self.und_distance)
        Dialog.setTabOrder(self.und_distance, self.und_xposition)
        Dialog.setTabOrder(self.und_xposition, self.und_yposition)
        Dialog.setTabOrder(self.und_yposition, self.und_xslit)
        Dialog.setTabOrder(self.und_xslit, self.und_yslit)
        Dialog.setTabOrder(self.und_yslit, self.und_xintpoints)
        Dialog.setTabOrder(self.und_xintpoints, self.und_yintpoints)
        Dialog.setTabOrder(self.und_yintpoints, self.und_estart)
        Dialog.setTabOrder(self.und_estart, self.und_eend)
        Dialog.setTabOrder(self.und_eend, self.und_edivisions)
        Dialog.setTabOrder(self.und_edivisions, self.advanced_button)
        Dialog.setTabOrder(self.advanced_button, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle("Undulator")
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Machine Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_energy.setInputMask(QtGui.QApplication.translate("Dialog", "5.3; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Current (mA)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_current.setText(QtGui.QApplication.translate("Dialog", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Beam Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">x</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigx.setText(QtGui.QApplication.translate("Dialog", "0.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">y</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigy.setText(QtGui.QApplication.translate("Dialog", "0.06", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">x1</span>(mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigx1.setText(QtGui.QApplication.translate("Dialog", "0.0250", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">y1</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigy1.setText(QtGui.QApplication.translate("Dialog", "0.0053", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Undulator Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Period Length (cm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_period.setText(QtGui.QApplication.translate("Dialog", "3.3", None, QtGui.QApplication.UnicodeUTF8))
        self.undn.setText(QtGui.QApplication.translate("Dialog", "Number of Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.und_nperiods.setText(QtGui.QApplication.translate("Dialog", "70", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Deflection Parameter K<span style=\" vertical-align:sub;\">x</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_kx.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Deflection Parameter K<span style=\" vertical-align:sub;\">y</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_ky.setText(QtGui.QApplication.translate("Dialog", "2.760", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Pinhole Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Distance (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_distance.setText(QtGui.QApplication.translate("Dialog", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "X center (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_xposition.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Y center (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_yposition.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "X size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_xslit.setText(QtGui.QApplication.translate("Dialog", "2.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Y size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_yslit.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "X Number of Points", None, QtGui.QApplication.UnicodeUTF8))
        self.und_xintpoints.setText(QtGui.QApplication.translate("Dialog", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Y Number of Points", None, QtGui.QApplication.UnicodeUTF8))
        self.und_yintpoints.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Scan Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Min energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_estart.setText(QtGui.QApplication.translate("Dialog", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Max energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_eend.setText(QtGui.QApplication.translate("Dialog", "50000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Energy Points", None, QtGui.QApplication.UnicodeUTF8))
        self.und_edivisions.setText(QtGui.QApplication.translate("Dialog", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "To adjust filters, region definitions, and other options, press the respective buttons in the main window", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_button.setText(QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))

