# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wiggler_ui.ui'
#
# Created: Fri Jul  6 15:23:15 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(498, 610)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 496, 606))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_27.setMargin(0)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.wig_title = QtGui.QLineEdit(self.groupBox_4)
        self.wig_title.setText(_fromUtf8(""))
        self.wig_title.setObjectName(_fromUtf8("wig_title"))
        self.verticalLayout_26.addWidget(self.wig_title)
        self.verticalLayout_27.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.wig_energy = QtGui.QLineEdit(self.groupBox)
        self.wig_energy.setObjectName(_fromUtf8("wig_energy"))
        self.verticalLayout_2.addWidget(self.wig_energy)
        self.verticalLayout_23.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_11.addWidget(self.label_16)
        self.wig_periods = QtGui.QLineEdit(self.groupBox)
        self.wig_periods.setObjectName(_fromUtf8("wig_periods"))
        self.verticalLayout_11.addWidget(self.wig_periods)
        self.verticalLayout_23.addLayout(self.verticalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.wig_current = QtGui.QLineEdit(self.groupBox)
        self.wig_current.setObjectName(_fromUtf8("wig_current"))
        self.verticalLayout.addWidget(self.wig_current)
        self.verticalLayout_24.addLayout(self.verticalLayout)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.wig_nperiods = QtGui.QLineEdit(self.groupBox)
        self.wig_nperiods.setObjectName(_fromUtf8("wig_nperiods"))
        self.verticalLayout_14.addWidget(self.wig_nperiods)
        self.verticalLayout_24.addLayout(self.verticalLayout_14)
        self.horizontalLayout.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addLayout(self.horizontalLayout)
        self.verticalLayout_27.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.wig_kx = QtGui.QLineEdit(self.groupBox_2)
        self.wig_kx.setObjectName(_fromUtf8("wig_kx"))
        self.verticalLayout_3.addWidget(self.wig_kx)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.wig_ky = QtGui.QLineEdit(self.groupBox_2)
        self.wig_ky.setObjectName(_fromUtf8("wig_ky"))
        self.verticalLayout_4.addWidget(self.wig_ky)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_27.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.wig_edivisions = QtGui.QLineEdit(self.groupBox_3)
        self.wig_edivisions.setObjectName(_fromUtf8("wig_edivisions"))
        self.verticalLayout_8.addWidget(self.wig_edivisions)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.wig_estart = QtGui.QLineEdit(self.groupBox_3)
        self.wig_estart.setObjectName(_fromUtf8("wig_estart"))
        self.verticalLayout_6.addWidget(self.wig_estart)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.wig_eend = QtGui.QLineEdit(self.groupBox_3)
        self.wig_eend.setObjectName(_fromUtf8("wig_eend"))
        self.verticalLayout_7.addWidget(self.wig_eend)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.wig_xintpoints = QtGui.QLineEdit(self.groupBox_3)
        self.wig_xintpoints.setObjectName(_fromUtf8("wig_xintpoints"))
        self.verticalLayout_10.addWidget(self.wig_xintpoints)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_9.addWidget(self.label_6)
        self.wig_yintpoints = QtGui.QLineEdit(self.groupBox_3)
        self.wig_yintpoints.setObjectName(_fromUtf8("wig_yintpoints"))
        self.verticalLayout_9.addWidget(self.wig_yintpoints)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_27.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.widget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_21.addWidget(self.label_14)
        self.wig_distance = QtGui.QLineEdit(self.groupBox_5)
        self.wig_distance.setObjectName(_fromUtf8("wig_distance"))
        self.verticalLayout_21.addWidget(self.wig_distance)
        self.horizontalLayout_5.addLayout(self.verticalLayout_21)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_18.addWidget(self.label_10)
        self.wig_xposition = QtGui.QLineEdit(self.groupBox_5)
        self.wig_xposition.setObjectName(_fromUtf8("wig_xposition"))
        self.verticalLayout_18.addWidget(self.wig_xposition)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_17.addWidget(self.label_11)
        self.wig_yposition = QtGui.QLineEdit(self.groupBox_5)
        self.wig_yposition.setObjectName(_fromUtf8("wig_yposition"))
        self.verticalLayout_17.addWidget(self.wig_yposition)
        self.verticalLayout_19.addLayout(self.verticalLayout_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_16.addWidget(self.label_12)
        self.wig_xslit = QtGui.QLineEdit(self.groupBox_5)
        self.wig_xslit.setObjectName(_fromUtf8("wig_xslit"))
        self.verticalLayout_16.addWidget(self.wig_xslit)
        self.verticalLayout_20.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_15.addWidget(self.label_13)
        self.wig_yslit = QtGui.QLineEdit(self.groupBox_5)
        self.wig_yslit.setObjectName(_fromUtf8("wig_yslit"))
        self.verticalLayout_15.addWidget(self.wig_yslit)
        self.verticalLayout_20.addLayout(self.verticalLayout_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.verticalLayout_22.addLayout(self.horizontalLayout_5)
        self.verticalLayout_27.addWidget(self.groupBox_5)
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_27.addWidget(self.label_23)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_27.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.wig_title, self.wig_energy)
        Dialog.setTabOrder(self.wig_energy, self.wig_current)
        Dialog.setTabOrder(self.wig_current, self.wig_periods)
        Dialog.setTabOrder(self.wig_periods, self.wig_nperiods)
        Dialog.setTabOrder(self.wig_nperiods, self.wig_kx)
        Dialog.setTabOrder(self.wig_kx, self.wig_ky)
        Dialog.setTabOrder(self.wig_ky, self.wig_edivisions)
        Dialog.setTabOrder(self.wig_edivisions, self.wig_estart)
        Dialog.setTabOrder(self.wig_estart, self.wig_eend)
        Dialog.setTabOrder(self.wig_eend, self.wig_xintpoints)
        Dialog.setTabOrder(self.wig_xintpoints, self.wig_yintpoints)
        Dialog.setTabOrder(self.wig_yintpoints, self.wig_distance)
        Dialog.setTabOrder(self.wig_distance, self.wig_xposition)
        Dialog.setTabOrder(self.wig_xposition, self.wig_yposition)
        Dialog.setTabOrder(self.wig_yposition, self.wig_yslit)
        Dialog.setTabOrder(self.wig_yslit, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle("Wiggler")
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Machine Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_energy.setText(QtGui.QApplication.translate("Dialog", "5.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Periods (cm)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_periods.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_periods.setPlaceholderText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Current (mA)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_current.setText(QtGui.QApplication.translate("Dialog", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Number of Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_nperiods.setText(QtGui.QApplication.translate("Dialog", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Wiggler Paramters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Deflection Parameter Kx", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_kx.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Deflection Parameter Ky", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_ky.setText(QtGui.QApplication.translate("Dialog", "8.74", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Plot Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Number Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_edivisions.setText(QtGui.QApplication.translate("Dialog", "2000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Min energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_estart.setText(QtGui.QApplication.translate("Dialog", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Max energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_eend.setText(QtGui.QApplication.translate("Dialog", "100000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Integration Points x", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_xintpoints.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Integration Points y", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_yintpoints.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Hole Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Distance (m)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_distance.setText(QtGui.QApplication.translate("Dialog", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "x Position (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_xposition.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "y Position (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_yposition.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "x slit (mm/mrad)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_xslit.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "y slit (mm/mrad)", None, QtGui.QApplication.UnicodeUTF8))
        self.wig_yslit.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "To adjust filters, region definitions, and other options, press the respective buttons in the main window", None, QtGui.QApplication.UnicodeUTF8))

