# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advancedoptions_ui.ui'
#
# Created: Thu Oct 11 17:13:56 2012
#      by: PyQt4 UI code generator 4.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AdvancedOptions(object):
    def setupUi(self, AdvancedOptions):
        AdvancedOptions.setObjectName(_fromUtf8("AdvancedOptions"))
        AdvancedOptions.resize(493, 512)
        self.layoutWidget = QtGui.QWidget(AdvancedOptions)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 2, 495, 512))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mode_1 = QtGui.QRadioButton(self.groupBox)
        self.mode_1.setObjectName(_fromUtf8("mode_1"))
        self.verticalLayout.addWidget(self.mode_1)
        self.mode_2 = QtGui.QRadioButton(self.groupBox)
        self.mode_2.setObjectName(_fromUtf8("mode_2"))
        self.verticalLayout.addWidget(self.mode_2)
        self.mode_3 = QtGui.QRadioButton(self.groupBox)
        self.mode_3.setObjectName(_fromUtf8("mode_3"))
        self.verticalLayout.addWidget(self.mode_3)
        self.mode_4 = QtGui.QRadioButton(self.groupBox)
        self.mode_4.setChecked(True)
        self.mode_4.setObjectName(_fromUtf8("mode_4"))
        self.verticalLayout.addWidget(self.mode_4)
        self.mode_5 = QtGui.QRadioButton(self.groupBox)
        self.mode_5.setObjectName(_fromUtf8("mode_5"))
        self.verticalLayout.addWidget(self.mode_5)
        self.mode_6 = QtGui.QRadioButton(self.groupBox)
        self.mode_6.setObjectName(_fromUtf8("mode_6"))
        self.verticalLayout.addWidget(self.mode_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.harmonic_1 = QtGui.QRadioButton(self.groupBox_3)
        self.harmonic_1.setChecked(True)
        self.harmonic_1.setObjectName(_fromUtf8("harmonic_1"))
        self.verticalLayout_5.addWidget(self.harmonic_1)
        self.harmonic_2 = QtGui.QRadioButton(self.groupBox_3)
        self.harmonic_2.setObjectName(_fromUtf8("harmonic_2"))
        self.verticalLayout_5.addWidget(self.harmonic_2)
        self.harmonic_3 = QtGui.QRadioButton(self.groupBox_3)
        self.harmonic_3.setObjectName(_fromUtf8("harmonic_3"))
        self.verticalLayout_5.addWidget(self.harmonic_3)
        self.harmonic_4 = QtGui.QRadioButton(self.groupBox_3)
        self.harmonic_4.setObjectName(_fromUtf8("harmonic_4"))
        self.verticalLayout_5.addWidget(self.harmonic_4)
        self.harmonic_4_custom = QtGui.QLineEdit(self.groupBox_3)
        self.harmonic_4_custom.setEnabled(False)
        self.harmonic_4_custom.setObjectName(_fromUtf8("harmonic_4_custom"))
        self.verticalLayout_5.addWidget(self.harmonic_4_custom)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.nphi = QtGui.QLineEdit(self.groupBox_4)
        self.nphi.setEnabled(False)
        self.nphi.setObjectName(_fromUtf8("nphi"))
        self.verticalLayout_7.addWidget(self.nphi)
        self.nalpha = QtGui.QLineEdit(self.groupBox_4)
        self.nalpha.setEnabled(False)
        self.nalpha.setObjectName(_fromUtf8("nalpha"))
        self.verticalLayout_7.addWidget(self.nalpha)
        self.calpha = QtGui.QLineEdit(self.groupBox_4)
        self.calpha.setEnabled(False)
        self.calpha.setObjectName(_fromUtf8("calpha"))
        self.verticalLayout_7.addWidget(self.calpha)
        self.nomega = QtGui.QLineEdit(self.groupBox_4)
        self.nomega.setEnabled(False)
        self.nomega.setObjectName(_fromUtf8("nomega"))
        self.verticalLayout_7.addWidget(self.nomega)
        self.comega = QtGui.QLineEdit(self.groupBox_4)
        self.comega.setEnabled(False)
        self.comega.setObjectName(_fromUtf8("comega"))
        self.verticalLayout_7.addWidget(self.comega)
        self.nsigma = QtGui.QLineEdit(self.groupBox_4)
        self.nsigma.setEnabled(False)
        self.nsigma.setObjectName(_fromUtf8("nsigma"))
        self.verticalLayout_7.addWidget(self.nsigma)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.method_1 = QtGui.QRadioButton(self.groupBox_2)
        self.method_1.setObjectName(_fromUtf8("method_1"))
        self.verticalLayout_3.addWidget(self.method_1)
        self.method_2 = QtGui.QRadioButton(self.groupBox_2)
        self.method_2.setObjectName(_fromUtf8("method_2"))
        self.verticalLayout_3.addWidget(self.method_2)
        self.method_3 = QtGui.QRadioButton(self.groupBox_2)
        self.method_3.setChecked(True)
        self.method_3.setObjectName(_fromUtf8("method_3"))
        self.verticalLayout_3.addWidget(self.method_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_17.addLayout(self.horizontalLayout_5)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_28.addWidget(self.label_20)
        self.estart = QtGui.QLineEdit(self.groupBox_6)
        self.estart.setEnabled(False)
        self.estart.setObjectName(_fromUtf8("estart"))
        self.verticalLayout_28.addWidget(self.estart)
        self.horizontalLayout_3.addLayout(self.verticalLayout_28)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_27.addWidget(self.label_21)
        self.eend = QtGui.QLineEdit(self.groupBox_6)
        self.eend.setEnabled(False)
        self.eend.setObjectName(_fromUtf8("eend"))
        self.verticalLayout_27.addWidget(self.eend)
        self.horizontalLayout_3.addLayout(self.verticalLayout_27)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_26.addWidget(self.label_22)
        self.ediv = QtGui.QLineEdit(self.groupBox_6)
        self.ediv.setEnabled(False)
        self.ediv.setObjectName(_fromUtf8("ediv"))
        self.verticalLayout_26.addWidget(self.ediv)
        self.horizontalLayout_3.addLayout(self.verticalLayout_26)
        self.verticalLayout_15.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_14.addWidget(self.label)
        self.xint = QtGui.QLineEdit(self.groupBox_6)
        self.xint.setEnabled(True)
        self.xint.setObjectName(_fromUtf8("xint"))
        self.verticalLayout_14.addWidget(self.xint)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_13.addWidget(self.label_8)
        self.yint = QtGui.QLineEdit(self.groupBox_6)
        self.yint.setEnabled(True)
        self.yint.setObjectName(_fromUtf8("yint"))
        self.verticalLayout_13.addWidget(self.yint)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_17.addWidget(self.groupBox_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.power_1 = QtGui.QRadioButton(self.groupBox_5)
        self.power_1.setObjectName(_fromUtf8("power_1"))
        self.horizontalLayout_6.addWidget(self.power_1)
        self.power_2 = QtGui.QRadioButton(self.groupBox_5)
        self.power_2.setChecked(True)
        self.power_2.setObjectName(_fromUtf8("power_2"))
        self.horizontalLayout_6.addWidget(self.power_2)
        self.power_3 = QtGui.QRadioButton(self.groupBox_5)
        self.power_3.setObjectName(_fromUtf8("power_3"))
        self.horizontalLayout_6.addWidget(self.power_3)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox_5)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)

        self.retranslateUi(AdvancedOptions)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), AdvancedOptions.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), AdvancedOptions.reject)
        QtCore.QObject.connect(self.harmonic_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.harmonic_4_custom.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AdvancedOptions)
        AdvancedOptions.setTabOrder(self.mode_1, self.mode_2)
        AdvancedOptions.setTabOrder(self.mode_2, self.mode_3)
        AdvancedOptions.setTabOrder(self.mode_3, self.mode_4)
        AdvancedOptions.setTabOrder(self.mode_4, self.mode_5)
        AdvancedOptions.setTabOrder(self.mode_5, self.mode_6)
        AdvancedOptions.setTabOrder(self.mode_6, self.harmonic_1)
        AdvancedOptions.setTabOrder(self.harmonic_1, self.harmonic_2)
        AdvancedOptions.setTabOrder(self.harmonic_2, self.harmonic_3)
        AdvancedOptions.setTabOrder(self.harmonic_3, self.harmonic_4)
        AdvancedOptions.setTabOrder(self.harmonic_4, self.harmonic_4_custom)
        AdvancedOptions.setTabOrder(self.harmonic_4_custom, self.nphi)
        AdvancedOptions.setTabOrder(self.nphi, self.nalpha)
        AdvancedOptions.setTabOrder(self.nalpha, self.calpha)
        AdvancedOptions.setTabOrder(self.calpha, self.nomega)
        AdvancedOptions.setTabOrder(self.nomega, self.comega)
        AdvancedOptions.setTabOrder(self.comega, self.nsigma)
        AdvancedOptions.setTabOrder(self.nsigma, self.method_1)
        AdvancedOptions.setTabOrder(self.method_1, self.method_2)
        AdvancedOptions.setTabOrder(self.method_2, self.method_3)

    def retranslateUi(self, AdvancedOptions):
        AdvancedOptions.setWindowTitle(QtGui.QApplication.translate("AdvancedOptions", "Advanced Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AdvancedOptions", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_1.setText(QtGui.QApplication.translate("AdvancedOptions", "Angular/Spatial flux density distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_2.setText(QtGui.QApplication.translate("AdvancedOptions", "Angular/spatial flux density spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_3.setText(QtGui.QApplication.translate("AdvancedOptions", "On-axis brilliance spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_4.setText(QtGui.QApplication.translate("AdvancedOptions", "Flux spectrum through a pinhole", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_5.setText(QtGui.QApplication.translate("AdvancedOptions", "Flux spectrum integrated over all angles", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_6.setText(QtGui.QApplication.translate("AdvancedOptions", "Power density and integrated power", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("AdvancedOptions", "Harmonics", None, QtGui.QApplication.UnicodeUTF8))
        self.harmonic_1.setText(QtGui.QApplication.translate("AdvancedOptions", "All harmonics", None, QtGui.QApplication.UnicodeUTF8))
        self.harmonic_2.setText(QtGui.QApplication.translate("AdvancedOptions", "Lowest order harmonic", None, QtGui.QApplication.UnicodeUTF8))
        self.harmonic_3.setText(QtGui.QApplication.translate("AdvancedOptions", "Harmonic #1", None, QtGui.QApplication.UnicodeUTF8))
        self.harmonic_4.setText(QtGui.QApplication.translate("AdvancedOptions", "Custom Harmonic Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("AdvancedOptions", "Intrinsic Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AdvancedOptions", "nφ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AdvancedOptions", "nα", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AdvancedOptions", "cα2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AdvancedOptions", "nω", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AdvancedOptions", "cω", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AdvancedOptions", "nσ", None, QtGui.QApplication.UnicodeUTF8))
        self.nphi.setText(QtGui.QApplication.translate("AdvancedOptions", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.nalpha.setText(QtGui.QApplication.translate("AdvancedOptions", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.calpha.setText(QtGui.QApplication.translate("AdvancedOptions", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.nomega.setText(QtGui.QApplication.translate("AdvancedOptions", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.comega.setText(QtGui.QApplication.translate("AdvancedOptions", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.nsigma.setText(QtGui.QApplication.translate("AdvancedOptions", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("AdvancedOptions", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.method_1.setText(QtGui.QApplication.translate("AdvancedOptions", "Non-zero emittance; finit-N", None, QtGui.QApplication.UnicodeUTF8))
        self.method_2.setText(QtGui.QApplication.translate("AdvancedOptions", "Zero emitance; finite-N", None, QtGui.QApplication.UnicodeUTF8))
        self.method_3.setText(QtGui.QApplication.translate("AdvancedOptions", "Non-zero emitance; infinite-N/convolution", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("AdvancedOptions", "Scan Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("AdvancedOptions", "Min energy (eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.estart.setText(QtGui.QApplication.translate("AdvancedOptions", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("AdvancedOptions", "Max energy (eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.eend.setText(QtGui.QApplication.translate("AdvancedOptions", "100000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("AdvancedOptions", "Energy Points", None, QtGui.QApplication.UnicodeUTF8))
        self.ediv.setText(QtGui.QApplication.translate("AdvancedOptions", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AdvancedOptions", "Integration Points x", None, QtGui.QApplication.UnicodeUTF8))
        self.xint.setText(QtGui.QApplication.translate("AdvancedOptions", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AdvancedOptions", "Integration Points y", None, QtGui.QApplication.UnicodeUTF8))
        self.yint.setText(QtGui.QApplication.translate("AdvancedOptions", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.power_1.setText(QtGui.QApplication.translate("AdvancedOptions", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.power_2.setText(QtGui.QApplication.translate("AdvancedOptions", "Power Density", None, QtGui.QApplication.UnicodeUTF8))
        self.power_3.setText(QtGui.QApplication.translate("AdvancedOptions", "Both", None, QtGui.QApplication.UnicodeUTF8))

