# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heatbump_w_ui.ui'
#
# Created: Mon Nov 19 18:16:24 2012
#      by: PyQt4 UI code generator 4.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HeatLoadMatrix(object):
    def setupUi(self, HeatLoadMatrix):
        HeatLoadMatrix.setObjectName(_fromUtf8("HeatLoadMatrix"))
        HeatLoadMatrix.resize(657, 547)
        self.centralwidget = QtGui.QWidget(HeatLoadMatrix)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1, 1, 651, 508))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.SourceConfiguration_groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SourceConfiguration_groupBox.sizePolicy().hasHeightForWidth())
        self.SourceConfiguration_groupBox.setSizePolicy(sizePolicy)
        self.SourceConfiguration_groupBox.setObjectName(_fromUtf8("SourceConfiguration_groupBox"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.SourceConfiguration_groupBox)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.splitter_3 = QtGui.QSplitter(self.SourceConfiguration_groupBox)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget1 = QtGui.QWidget(self.splitter_3)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.source_und = QtGui.QRadioButton(self.widget1)
        self.source_und.setChecked(True)
        self.source_und.setObjectName(_fromUtf8("source_und"))
        self.verticalLayout.addWidget(self.source_und)
        self.source_wig = QtGui.QRadioButton(self.widget1)
        self.source_wig.setObjectName(_fromUtf8("source_wig"))
        self.verticalLayout.addWidget(self.source_wig)
        self.source_bend = QtGui.QRadioButton(self.widget1)
        self.source_bend.setEnabled(False)
        self.source_bend.setObjectName(_fromUtf8("source_bend"))
        self.verticalLayout.addWidget(self.source_bend)
        self.config_source = QtGui.QPushButton(self.splitter_3)
        self.config_source.setObjectName(_fromUtf8("config_source"))
        self.layoutWidget_6 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SelectedSource_Label = QtGui.QLabel(self.layoutWidget_6)
        self.SelectedSource_Label.setObjectName(_fromUtf8("SelectedSource_Label"))
        self.horizontalLayout_2.addWidget(self.SelectedSource_Label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.source_selected_text = QtGui.QTextEdit(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_selected_text.sizePolicy().hasHeightForWidth())
        self.source_selected_text.setSizePolicy(sizePolicy)
        self.source_selected_text.setMaximumSize(QtCore.QSize(16777215, 20))
        self.source_selected_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.source_selected_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.source_selected_text.setReadOnly(True)
        self.source_selected_text.setObjectName(_fromUtf8("source_selected_text"))
        self.horizontalLayout_2.addWidget(self.source_selected_text)
        self.verticalLayout_14.addWidget(self.splitter_3)
        self.verticalLayout_15.addWidget(self.SourceConfiguration_groupBox)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.ObjectConfiguration_groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjectConfiguration_groupBox.sizePolicy().hasHeightForWidth())
        self.ObjectConfiguration_groupBox.setSizePolicy(sizePolicy)
        self.ObjectConfiguration_groupBox.setObjectName(_fromUtf8("ObjectConfiguration_groupBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.ObjectConfiguration_groupBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.splitter_2 = QtGui.QSplitter(self.ObjectConfiguration_groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ObjectMaterial_label = QtGui.QLabel(self.layoutWidget_2)
        self.ObjectMaterial_label.setObjectName(_fromUtf8("ObjectMaterial_label"))
        self.horizontalLayout_5.addWidget(self.ObjectMaterial_label)
        spacerItem1 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.mat = QtGui.QTextEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat.sizePolicy().hasHeightForWidth())
        self.mat.setSizePolicy(sizePolicy)
        self.mat.setMinimumSize(QtCore.QSize(0, 20))
        self.mat.setMaximumSize(QtCore.QSize(75, 20))
        self.mat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mat.setObjectName(_fromUtf8("mat"))
        self.horizontalLayout_5.addWidget(self.mat)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.DistancetotheSource_label = QtGui.QLabel(self.layoutWidget_2)
        self.DistancetotheSource_label.setObjectName(_fromUtf8("DistancetotheSource_label"))
        self.horizontalLayout_6.addWidget(self.DistancetotheSource_label)
        spacerItem2 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.dist = QtGui.QTextEdit(self.layoutWidget_2)
        self.dist.setMinimumSize(QtCore.QSize(75, 20))
        self.dist.setMaximumSize(QtCore.QSize(75, 20))
        self.dist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dist.setObjectName(_fromUtf8("dist"))
        self.horizontalLayout_6.addWidget(self.dist)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.InclinationtotheBeam_label = QtGui.QLabel(self.layoutWidget_2)
        self.InclinationtotheBeam_label.setObjectName(_fromUtf8("InclinationtotheBeam_label"))
        self.horizontalLayout_7.addWidget(self.InclinationtotheBeam_label)
        spacerItem3 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.deg = QtGui.QTextEdit(self.layoutWidget_2)
        self.deg.setEnabled(False)
        self.deg.setMinimumSize(QtCore.QSize(75, 20))
        self.deg.setMaximumSize(QtCore.QSize(75, 20))
        self.deg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.deg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.deg.setObjectName(_fromUtf8("deg"))
        self.horizontalLayout_7.addWidget(self.deg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.config_region = QtGui.QPushButton(self.splitter_2)
        self.config_region.setObjectName(_fromUtf8("config_region"))
        self.verticalLayout_11.addWidget(self.splitter_2)
        self.verticalLayout_13.addWidget(self.ObjectConfiguration_groupBox)
        self.ObjectMeshConfiguration_groupBox = QtGui.QGroupBox(self.widget)
        self.ObjectMeshConfiguration_groupBox.setObjectName(_fromUtf8("ObjectMeshConfiguration_groupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.ObjectMeshConfiguration_groupBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mesh_uniform = QtGui.QRadioButton(self.ObjectMeshConfiguration_groupBox)
        self.mesh_uniform.setChecked(True)
        self.mesh_uniform.setObjectName(_fromUtf8("mesh_uniform"))
        self.verticalLayout_2.addWidget(self.mesh_uniform)
        self.mesh_progressive = QtGui.QRadioButton(self.ObjectMeshConfiguration_groupBox)
        self.mesh_progressive.setEnabled(False)
        self.mesh_progressive.setObjectName(_fromUtf8("mesh_progressive"))
        self.verticalLayout_2.addWidget(self.mesh_progressive)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ConfigureMesh_pushButton_2 = QtGui.QPushButton(self.ObjectMeshConfiguration_groupBox)
        self.ConfigureMesh_pushButton_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigureMesh_pushButton_2.sizePolicy().hasHeightForWidth())
        self.ConfigureMesh_pushButton_2.setSizePolicy(sizePolicy)
        self.ConfigureMesh_pushButton_2.setObjectName(_fromUtf8("ConfigureMesh_pushButton_2"))
        self.verticalLayout_8.addWidget(self.ConfigureMesh_pushButton_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.ObjectMeshConfiguration_groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.mesh_level = QtGui.QLineEdit(self.ObjectMeshConfiguration_groupBox)
        self.mesh_level.setEnabled(False)
        self.mesh_level.setObjectName(_fromUtf8("mesh_level"))
        self.horizontalLayout_11.addWidget(self.mesh_level)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_13.addWidget(self.ObjectMeshConfiguration_groupBox)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.FilterConfiguration_groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterConfiguration_groupBox.sizePolicy().hasHeightForWidth())
        self.FilterConfiguration_groupBox.setSizePolicy(sizePolicy)
        self.FilterConfiguration_groupBox.setObjectName(_fromUtf8("FilterConfiguration_groupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.FilterConfiguration_groupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.FilterConfiguration_treeWidget = QtGui.QTreeWidget(self.FilterConfiguration_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterConfiguration_treeWidget.sizePolicy().hasHeightForWidth())
        self.FilterConfiguration_treeWidget.setSizePolicy(sizePolicy)
        self.FilterConfiguration_treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FilterConfiguration_treeWidget.setIndentation(20)
        self.FilterConfiguration_treeWidget.setRootIsDecorated(False)
        self.FilterConfiguration_treeWidget.setItemsExpandable(False)
        self.FilterConfiguration_treeWidget.setAllColumnsShowFocus(True)
        self.FilterConfiguration_treeWidget.setObjectName(_fromUtf8("FilterConfiguration_treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.FilterConfiguration_treeWidget)
        self.FilterConfiguration_treeWidget.header().setDefaultSectionSize(60)
        self.FilterConfiguration_treeWidget.header().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.FilterConfiguration_treeWidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.AddNewFilter_pushButton = QtGui.QPushButton(self.FilterConfiguration_groupBox)
        self.AddNewFilter_pushButton.setObjectName(_fromUtf8("AddNewFilter_pushButton"))
        self.verticalLayout_3.addWidget(self.AddNewFilter_pushButton)
        self.RemoveFilter_pushButton = QtGui.QPushButton(self.FilterConfiguration_groupBox)
        self.RemoveFilter_pushButton.setObjectName(_fromUtf8("RemoveFilter_pushButton"))
        self.verticalLayout_3.addWidget(self.RemoveFilter_pushButton)
        spacerItem4 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14.addWidget(self.FilterConfiguration_groupBox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter = QtGui.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.Options_groupBox = QtGui.QGroupBox(self.splitter)
        self.Options_groupBox.setObjectName(_fromUtf8("Options_groupBox"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.Options_groupBox)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.power_power = QtGui.QRadioButton(self.Options_groupBox)
        self.power_power.setObjectName(_fromUtf8("power_power"))
        self.verticalLayout_6.addWidget(self.power_power)
        self.power_density = QtGui.QRadioButton(self.Options_groupBox)
        self.power_density.setObjectName(_fromUtf8("power_density"))
        self.verticalLayout_6.addWidget(self.power_density)
        self.power_both = QtGui.QRadioButton(self.Options_groupBox)
        self.power_both.setObjectName(_fromUtf8("power_both"))
        self.verticalLayout_6.addWidget(self.power_both)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.OutputFileName_label = QtGui.QLabel(self.Options_groupBox)
        self.OutputFileName_label.setObjectName(_fromUtf8("OutputFileName_label"))
        self.horizontalLayout_8.addWidget(self.OutputFileName_label)
        self.title = QtGui.QTextEdit(self.Options_groupBox)
        self.title.setMinimumSize(QtCore.QSize(0, 20))
        self.title.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.title.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.title.setObjectName(_fromUtf8("title"))
        self.horizontalLayout_8.addWidget(self.title)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.config_go = QtGui.QPushButton(self.splitter)
        self.config_go.setObjectName(_fromUtf8("config_go"))
        self.config_abort = QtGui.QPushButton(self.splitter)
        self.config_abort.setObjectName(_fromUtf8("config_abort"))
        self.verticalLayout_7.addWidget(self.splitter)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.status_bar = QtGui.QProgressBar(self.widget)
        self.status_bar.setProperty("value", 0)
        self.status_bar.setTextVisible(False)
        self.status_bar.setInvertedAppearance(False)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        self.verticalLayout_5.addWidget(self.status_bar)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem5 = QtGui.QSpacerItem(198, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.status_label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.horizontalLayout_9.addWidget(self.status_label)
        spacerItem6 = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_15.addLayout(self.verticalLayout_7)
        HeatLoadMatrix.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(HeatLoadMatrix)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSpectral_Data = QtGui.QMenu(self.menubar)
        self.menuSpectral_Data.setObjectName(_fromUtf8("menuSpectral_Data"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        HeatLoadMatrix.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(HeatLoadMatrix)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        HeatLoadMatrix.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(HeatLoadMatrix)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSave_Parameters = QtGui.QAction(HeatLoadMatrix)
        self.actionSave_Parameters.setObjectName(_fromUtf8("actionSave_Parameters"))
        self.actionOpen_Parameters = QtGui.QAction(HeatLoadMatrix)
        self.actionOpen_Parameters.setObjectName(_fromUtf8("actionOpen_Parameters"))
        self.actionSave_Spectral_Data = QtGui.QAction(HeatLoadMatrix)
        self.actionSave_Spectral_Data.setObjectName(_fromUtf8("actionSave_Spectral_Data"))
        self.actionSave_Spectral_Data_2 = QtGui.QAction(HeatLoadMatrix)
        self.actionSave_Spectral_Data_2.setObjectName(_fromUtf8("actionSave_Spectral_Data_2"))
        self.actionImport_Spectral_Data = QtGui.QAction(HeatLoadMatrix)
        self.actionImport_Spectral_Data.setObjectName(_fromUtf8("actionImport_Spectral_Data"))
        self.actionSave_spectrum = QtGui.QAction(HeatLoadMatrix)
        self.actionSave_spectrum.setObjectName(_fromUtf8("actionSave_spectrum"))
        self.actionImport_Spectrum = QtGui.QAction(HeatLoadMatrix)
        self.actionImport_Spectrum.setObjectName(_fromUtf8("actionImport_Spectrum"))
        self.actionHelp = QtGui.QAction(HeatLoadMatrix)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionPaper = QtGui.QAction(HeatLoadMatrix)
        self.actionPaper.setObjectName(_fromUtf8("actionPaper"))
        self.actionAbout = QtGui.QAction(HeatLoadMatrix)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionGo = QtGui.QAction(HeatLoadMatrix)
        self.actionGo.setObjectName(_fromUtf8("actionGo"))
        self.actionAbort = QtGui.QAction(HeatLoadMatrix)
        self.actionAbort.setObjectName(_fromUtf8("actionAbort"))
        self.actionView_Results = QtGui.QAction(HeatLoadMatrix)
        self.actionView_Results.setObjectName(_fromUtf8("actionView_Results"))
        self.actionConfigure_XOP = QtGui.QAction(HeatLoadMatrix)
        self.actionConfigure_XOP.setObjectName(_fromUtf8("actionConfigure_XOP"))
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menuFile.addAction(self.actionOpen_Parameters)
        self.menuSpectral_Data.addAction(self.actionSave_spectrum)
        self.menuSpectral_Data.addAction(self.actionImport_Spectrum)
        self.menuSpectral_Data.addAction(self.actionConfigure_XOP)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionPaper)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRun.addAction(self.actionGo)
        self.menuRun.addAction(self.actionAbort)
        self.menuRun.addAction(self.actionView_Results)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuSpectral_Data.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HeatLoadMatrix)
        QtCore.QMetaObject.connectSlotsByName(HeatLoadMatrix)

    def retranslateUi(self, HeatLoadMatrix):
        HeatLoadMatrix.setWindowTitle(QtGui.QApplication.translate("HeatLoadMatrix", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.SourceConfiguration_groupBox.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Source Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.source_und.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Undulator", None, QtGui.QApplication.UnicodeUTF8))
        self.source_wig.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Wiggler", None, QtGui.QApplication.UnicodeUTF8))
        self.source_bend.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Bend Magnet", None, QtGui.QApplication.UnicodeUTF8))
        self.config_source.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Configure Source", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectedSource_Label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Selected Source:", None, QtGui.QApplication.UnicodeUTF8))
        self.source_selected_text.setHtml(QtGui.QApplication.translate("HeatLoadMatrix", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">No source selected.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectConfiguration_groupBox.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Object Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectMaterial_label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Material:", None, QtGui.QApplication.UnicodeUTF8))
        self.mat.setToolTip(QtGui.QApplication.translate("HeatLoadMatrix", "<html><head/><body><p>Enter the elemental symbol of the object of interest. This is not case sensitive.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.DistancetotheSource_label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Distance to the Source (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.dist.setToolTip(QtGui.QApplication.translate("HeatLoadMatrix", "<html><head/><body><p>Enter the distance from the object to the source in meters.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.InclinationtotheBeam_label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Inclination to the Beam (deg):", None, QtGui.QApplication.UnicodeUTF8))
        self.deg.setToolTip(QtGui.QApplication.translate("HeatLoadMatrix", "<html><head/><body><p>Enter the inclination with respect to the beam in degrees: 0 is parallel, 90 is normal.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_region.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Configure Region", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectMeshConfiguration_groupBox.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Object Mesh Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_uniform.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Uniform Meshing", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_progressive.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Progressive Meshing", None, QtGui.QApplication.UnicodeUTF8))
        self.ConfigureMesh_pushButton_2.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Configure Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Mesh Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterConfiguration_groupBox.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Filter Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterConfiguration_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("HeatLoadMatrix", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterConfiguration_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("HeatLoadMatrix", "Thickness (µm)", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.FilterConfiguration_treeWidget.isSortingEnabled()
        self.FilterConfiguration_treeWidget.setSortingEnabled(False)
        self.FilterConfiguration_treeWidget.setSortingEnabled(__sortingEnabled)
        self.AddNewFilter_pushButton.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Add New Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveFilter_pushButton.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Remove Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.Options_groupBox.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Output Options", None, QtGui.QApplication.UnicodeUTF8))
        self.power_power.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Power (W)", None, QtGui.QApplication.UnicodeUTF8))
        self.power_density.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Power Density (W/m^3)", None, QtGui.QApplication.UnicodeUTF8))
        self.power_both.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputFileName_label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Output File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.config_go.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.config_abort.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Ready to Start", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSpectral_Data.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Spectral Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("HeatLoadMatrix", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Parameters.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Save Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Parameters.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Open Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Spectral_Data.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Save Spectral Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Spectral_Data_2.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Save Spectral Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Spectral_Data.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Import Spectral Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_spectrum.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Save Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Spectrum.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Import Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaper.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Paper", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("HeatLoadMatrix", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbort.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Results.setText(QtGui.QApplication.translate("HeatLoadMatrix", "View Results", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_XOP.setText(QtGui.QApplication.translate("HeatLoadMatrix", "Configure XOP", None, QtGui.QApplication.UnicodeUTF8))

