# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'undulator_ui.ui'
#
# Created: Thu Dec  6 08:50:18 2012
#      by: PyQt4 UI code generator 4.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(505, 283)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 281))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.und_energy = QtGui.QLineEdit(self.groupBox)
        self.und_energy.setInputMask(_fromUtf8(""))
        self.und_energy.setObjectName(_fromUtf8("und_energy"))
        self.verticalLayout.addWidget(self.und_energy)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.und_current = QtGui.QLineEdit(self.groupBox)
        self.und_current.setObjectName(_fromUtf8("und_current"))
        self.verticalLayout_2.addWidget(self.und_current)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.verticalLayout_15.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.und_sigx = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigx.setObjectName(_fromUtf8("und_sigx"))
        self.verticalLayout_3.addWidget(self.und_sigx)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.und_sigy = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigy.setObjectName(_fromUtf8("und_sigy"))
        self.verticalLayout_4.addWidget(self.und_sigy)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.und_sigx1 = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigx1.setObjectName(_fromUtf8("und_sigx1"))
        self.verticalLayout_5.addWidget(self.und_sigx1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.und_sigy1 = QtGui.QLineEdit(self.groupBox_2)
        self.und_sigy1.setObjectName(_fromUtf8("und_sigy1"))
        self.verticalLayout_6.addWidget(self.und_sigy1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout_15.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.und_period = QtGui.QLineEdit(self.groupBox_3)
        self.und_period.setObjectName(_fromUtf8("und_period"))
        self.verticalLayout_7.addWidget(self.und_period)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.undn = QtGui.QLabel(self.groupBox_3)
        self.undn.setObjectName(_fromUtf8("undn"))
        self.verticalLayout_8.addWidget(self.undn)
        self.und_nperiods = QtGui.QLineEdit(self.groupBox_3)
        self.und_nperiods.setObjectName(_fromUtf8("und_nperiods"))
        self.verticalLayout_8.addWidget(self.und_nperiods)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.und_kx = QtGui.QLineEdit(self.groupBox_3)
        self.und_kx.setObjectName(_fromUtf8("und_kx"))
        self.verticalLayout_9.addWidget(self.und_kx)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.und_ky = QtGui.QLineEdit(self.groupBox_3)
        self.und_ky.setObjectName(_fromUtf8("und_ky"))
        self.verticalLayout_10.addWidget(self.und_ky)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.verticalLayout_15.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.advanced_button = QtGui.QPushButton(self.layoutWidget)
        self.advanced_button.setObjectName(_fromUtf8("advanced_button"))
        self.horizontalLayout_4.addWidget(self.advanced_button)
        self.default_button = QtGui.QPushButton(self.layoutWidget)
        self.default_button.setObjectName(_fromUtf8("default_button"))
        self.horizontalLayout_4.addWidget(self.default_button)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.und_energy, self.und_current)
        Dialog.setTabOrder(self.und_current, self.und_sigx)
        Dialog.setTabOrder(self.und_sigx, self.und_sigy)
        Dialog.setTabOrder(self.und_sigy, self.und_sigx1)
        Dialog.setTabOrder(self.und_sigx1, self.und_sigy1)
        Dialog.setTabOrder(self.und_sigy1, self.und_period)
        Dialog.setTabOrder(self.und_period, self.und_nperiods)
        Dialog.setTabOrder(self.und_nperiods, self.und_kx)
        Dialog.setTabOrder(self.und_kx, self.und_ky)
        Dialog.setTabOrder(self.und_ky, self.advanced_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Undulator", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Machine Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Beam Energy (GeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_energy.setText(QtGui.QApplication.translate("Dialog", "5.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Beam Current (mA)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_current.setText(QtGui.QApplication.translate("Dialog", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Beam Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">x</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigx.setText(QtGui.QApplication.translate("Dialog", "0.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">y</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigy.setText(QtGui.QApplication.translate("Dialog", "0.06", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">x1</span>(mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigx1.setText(QtGui.QApplication.translate("Dialog", "0.0250", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>σ<span style=\" vertical-align:sub;\">y1</span> (mm)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_sigy1.setText(QtGui.QApplication.translate("Dialog", "0.0053", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Undulator Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Period Length (cm)", None, QtGui.QApplication.UnicodeUTF8))
        self.und_period.setText(QtGui.QApplication.translate("Dialog", "3.3", None, QtGui.QApplication.UnicodeUTF8))
        self.undn.setText(QtGui.QApplication.translate("Dialog", "Number of Periods", None, QtGui.QApplication.UnicodeUTF8))
        self.und_nperiods.setText(QtGui.QApplication.translate("Dialog", "70", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Deflection Parameter K<span style=\" vertical-align:sub;\">x</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_kx.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Deflection Parameter K<span style=\" vertical-align:sub;\">y</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.und_ky.setText(QtGui.QApplication.translate("Dialog", "2.760", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_button.setText(QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.default_button.setText(QtGui.QApplication.translate("Dialog", "Default Values", None, QtGui.QApplication.UnicodeUTF8))

